import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, Navigate, useLocation } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { listBusinesses } from '../lib/data';
import { supabase } from '../lib/supabase';
import { autoEnglishFromVietnamese } from '../lib/i18n';
import { formatCompactMoney } from '../lib/format';

type AdminTab = 'overview' | 'businesses' | 'business_review' | 'investors' | 'investor_contacts' | 'payments' | 'promos' | 'quality' | 'requests' | 'market_partners' | 'logs' | 'settings';
const pathTabs: Record<string, AdminTab> = {
  '': 'overview', overview:'overview', businesses:'businesses', 'business-review':'business_review', investors:'investors', 'investor-imports':'investors', advisors:'settings', affiliates:'market_partners', 'market-partners':'market_partners', payments:'payments', promo:'promos', proposals:'requests', 'data-requests':'requests', 'valuation-rules':'quality', 'quality-criteria':'quality', seo:'settings', imports:'settings', security:'settings', audit:'logs', 'email-queue':'settings', 'feature-flags':'settings', settings:'settings'
};
const tabs: {id:AdminTab; label:string; href:string}[] = [
  {id:'overview',label:'Overview',href:'/admin'},
  {id:'businesses',label:'Businesses',href:'/admin/businesses'},
  {id:'business_review',label:'Business Review',href:'/admin/business-review'},
  {id:'investors',label:'Investors',href:'/admin/investors'},
  {id:'investor_contacts',label:'Investor Contacts',href:'/admin/investor-imports'},
  {id:'payments',label:'Payments',href:'/admin/payments'},
  {id:'promos',label:'Promo Codes',href:'/admin/promo'},
  {id:'quality',label:'Quality Criteria',href:'/admin/quality-criteria'},
  {id:'requests',label:'Data Requests',href:'/admin/data-requests'},
  {id:'market_partners',label:'Market Partners',href:'/admin/market-partners'},
  {id:'logs',label:'Audit Logs',href:'/admin/audit'},
  {id:'settings',label:'Settings',href:'/admin/settings'}
];
function resolveTab(pathname:string):AdminTab { const suffix = pathname.replace('/admin','').replace(/^\//,'').split('/')[0]; return pathTabs[suffix] || 'overview'; }

export default function Admin(){
  const {profile,loading}=useAuth();
  const location = useLocation();
  const [tab,setTab]=useState<AdminTab>(()=>resolveTab(location.pathname));
  const [businesses,setBusinesses]=useState<any[]>([]);
  const [investors,setInvestors]=useState<any[]>([]);
  const [profiles,setProfiles]=useState<any[]>([]);
  const [promos,setPromos]=useState<any[]>([]);
  const [criteria,setCriteria]=useState<any[]>([]);
  const [requests,setRequests]=useState<any[]>([]);
  const [payments,setPayments]=useState<any[]>([]);
  const [logs,setLogs]=useState<any[]>([]);
  const [msg,setMsg]=useState('');
  const [error,setError]=useState('');
  const [busy,setBusy]=useState(false);
  const [search,setSearch]=useState('');

  useEffect(()=>setTab(resolveTab(location.pathname)),[location.pathname]);

  async function load(){
    if(profile?.role !== 'admin') return;
    setBusy(true); setError('');
    try {
      const [biz, invRes, profRes, promoRes, criteriaRes, reqRes, payRes, logRes] = await Promise.all([
        listBusinesses({includeHidden:true}).catch(()=>[]),
        supabase.from('investors').select('*').order('admin_priority',{ascending:false}).order('created_at',{ascending:false}).limit(2000),
        supabase.from('profiles').select('*').order('created_at',{ascending:false}).limit(2000),
        supabase.from('promo_codes').select('*').order('created_at',{ascending:false}),
        supabase.from('quality_criteria').select('*').order('sort_order'),
        supabase.from('request_data').select('*, businesses(title_vi,title_en,public_code,slug), investors(title_en,code,type)').order('created_at',{ascending:false}),
        supabase.from('payment_orders').select('*').order('created_at',{ascending:false}).limit(200),
        supabase.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(80)
      ]);
      setBusinesses(biz || []); setInvestors(invRes.data||[]); setProfiles(profRes.data||[]); setPromos(promoRes.data||[]); setCriteria(criteriaRes.data||[]); setRequests(reqRes.data||[]); setPayments(payRes.data||[]); setLogs(logRes.data||[]);
      const firstErr = invRes.error || profRes.error || promoRes.error || criteriaRes.error || reqRes.error || payRes.error || logRes.error;
      if(firstErr) setError(firstErr.message);
    } catch(e:any){ setError(e?.message || 'Could not load admin data.'); }
    finally { setBusy(false); }
  }
  useEffect(()=>{ if(profile?.role==='admin') load(); },[profile?.role]);

  if(loading)return <section className="section"><div className="container empty">Loading admin...</div></section>;
  if(profile?.role!=='admin') return <Navigate to="/login?next=/admin" replace/>;

  const pendingBusinesses = businesses.filter(b=>b.status === 'pending_admin_review' || b.pending_changes_json);
  const hiddenBusinesses = businesses.filter(b=>!b.visible || b.status === 'hidden');
  const pendingProfiles = profiles.filter(p=>String(p.status||'').includes('pending'));
  const marketPartners = profiles.filter(p=>p.role === 'affiliate');
  const filteredBusinesses = filterRows(businesses, search, ['title_vi','title_en','company_name_private','public_code','industry','status']);
  const filteredInvestors = filterRows(investors, search, ['title_vi','title_en','private_name','private_email','code','type','country']);

  async function logAction(action:string, entity_type:string, entity_id:string, detail:any={}){
    try { await supabase.from('audit_logs').insert({actor_id:profile.id,action,entity_type,entity_id,detail}); } catch { /* audit logging is non-blocking */ }
  }
  async function toggleBusiness(b:any){const nextVisible=!b.visible; const {error}=await supabase.from('businesses').update({visible:nextVisible,status:nextVisible?'active':'hidden'}).eq('id',b.id); if(!error) await logAction(nextVisible?'show_business':'hide_business','business',b.id,{public_code:b.public_code}); setMsg(error?error.message:'Business visibility updated.'); load();}
  async function approvePending(b:any){
    let patch = b.pending_changes_json || {};
    let {error}=await supabase.rpc('approve_business_pending',{business_uuid:b.id});
    if(error && Object.keys(patch).length){
      const fallback = {...patch, pending_changes_json:null, status:'active', updated_at:new Date().toISOString()};
      const r = await supabase.from('businesses').update(fallback).eq('id',b.id); error = r.error;
    }
    if(!error) await logAction('approve_business_pending','business',b.id,{public_code:b.public_code});
    setMsg(error?error.message:'Pending changes approved.'); load();
  }
  async function saveBusiness(e:FormEvent,b:any){e.preventDefault(); const fd=new FormData(e.currentTarget as HTMLFormElement); const patch:any={title_vi:fd.get('title_vi'),title_en:autoEnglishFromVietnamese(String(fd.get('title_vi')||'')),industry:fd.get('industry'),deal_type:fd.get('deal_type'),revenue_2025:Number(fd.get('revenue_2025')),ebitda_margin:Number(fd.get('ebitda_margin')),ask_amount:Number(fd.get('ask_amount')),stake_pct:Number(fd.get('stake_pct')),quality_score:Number(fd.get('quality_score')),data_confidence:Number(fd.get('data_confidence')),visible:fd.get('visible')==='on',plan:fd.get('plan'),status:fd.get('status')}; const {error}=await supabase.from('businesses').update(patch).eq('id',b.id); if(!error) await logAction('save_business','business',b.id,{public_code:b.public_code}); setMsg(error?error.message:'Business updated directly by admin.'); load();}
  async function toggleInvestor(i:any){const nextVisible=!i.visible; const {error}=await supabase.from('investors').update({visible:nextVisible,status:nextVisible?'active':'hidden'}).eq('id',i.id); if(!error) await logAction(nextVisible?'show_investor':'hide_investor','investor',i.id,{code:i.code}); setMsg(error?error.message:'Investor visibility updated.'); load();}
  async function saveInvestor(e:FormEvent,i:any){e.preventDefault(); const fd=new FormData(e.currentTarget as HTMLFormElement); const industries=String(fd.get('industries')||'').split(',').map(s=>s.trim()).filter(Boolean); const deal_types=String(fd.get('deal_types')||'').split(',').map(s=>s.trim()).filter(Boolean); const {error}=await supabase.from('investors').update({title_en:fd.get('title_en'),title_vi:fd.get('title_vi'),desc_en:fd.get('desc_en'),type:fd.get('type'),country:fd.get('country'),country_iso2:fd.get('country_iso2'),industries,deal_types,ticket_min:Number(fd.get('ticket_min')),ticket_max:Number(fd.get('ticket_max')),verified:fd.get('verified')==='on',admin_priority:fd.get('admin_priority')==='on',private_name:fd.get('private_name'),private_website:fd.get('private_website'),private_email:fd.get('private_email'),private_phone:fd.get('private_phone')}).eq('id',i.id); if(!error) await logAction('save_investor','investor',i.id,{code:i.code}); setMsg(error?error.message:'Investor updated.'); load();}
  async function approveProfile(p:any){const {error}=await supabase.from('profiles').update({status:'active',dashboard_login_enabled:true}).eq('id',p.id); if(!error) await logAction('approve_profile','profile',p.id,{role:p.role}); setMsg(error?error.message:'Profile approved and dashboard enabled.'); load();}
  async function hideProfile(p:any){const {error}=await supabase.from('profiles').update({status:'hidden',dashboard_login_enabled:false}).eq('id',p.id); if(!error) await logAction('hide_profile','profile',p.id,{role:p.role}); setMsg(error?error.message:'Profile hidden.'); load();}
  async function createPromo(e:FormEvent){e.preventDefault(); const fd=new FormData(e.currentTarget as HTMLFormElement); const {error}=await supabase.from('promo_codes').insert({code:String(fd.get('code')||'').toUpperCase(),description:fd.get('description'),role:fd.get('role'),discount_pct:Number(fd.get('discount_pct')),quota_total:Number(fd.get('quota_total')),starts_at:fd.get('starts_at') || new Date().toISOString(),ends_at:fd.get('ends_at'),active:true,created_by:profile.id}); if(!error) await logAction('create_promo','promo',String(fd.get('code')||''),{}); setMsg(error?error.message:'Promo created.'); load();}
  async function saveCriterion(e:FormEvent,c:any){e.preventDefault(); const fd=new FormData(e.currentTarget as HTMLFormElement); const {error}=await supabase.from('quality_criteria').update({label_vi:fd.get('label_vi'),label_en:fd.get('label_en'),weight:Number(fd.get('weight')),sort_order:Number(fd.get('sort_order')||0),active:fd.get('active')==='on'}).eq('id',c.id); if(!error) await logAction('save_quality_criterion','quality_criteria',c.id,{}); setMsg(error?error.message:'Criterion updated.'); load();}
  async function markRequest(r:any,status:string){const {error}=await supabase.from('request_data').update({status}).eq('id',r.id); if(!error) await logAction('mark_data_request','request_data',r.id,{status}); setMsg(error?error.message:'Request updated.'); load();}
  async function markPayment(row:any,status:string){const {error}=await supabase.from('payment_orders').update({status,updated_at:new Date().toISOString()}).eq('id',row.id); if(!error) await logAction('mark_payment','payment_order',row.id,{status}); setMsg(error?error.message:'Payment updated.'); load();}

  return <section className="dashboard-page admin-dashboard-page"><div className="container dashboard-shell admin-shell"><aside className="dashboard-side admin-side"><div className="dash-brand"><span className="pill red">Admin</span><b>Deals68</b></div>{tabs.map(item=><Link key={item.id} to={item.href} onClick={()=>setTab(item.id)} className={`side-link ${tab===item.id?'active':''}`}>{item.label}</Link>)}</aside><main className="dashboard-main"><div className="dashboard-top"><div><span className="badge-title gold">★ Admin Control Center</span><h1>Deals68 Admin</h1><p className="muted">Manage businesses, investors, payments, promo codes, quality criteria and requests.</p></div><button className="btn secondary" onClick={load}>{busy?'Loading...':'Refresh'}</button></div>{msg&&<div className="notice">{msg}</div>}{error&&<div className="notice warn">{error}</div>}<div className="admin-search"><input className="input" placeholder="Search businesses/investors/profiles..." value={search} onChange={e=>setSearch(e.target.value)}/></div>

  {tab==='overview'&&<div className="dashboard-grid"><Metric title="Businesses" value={String(businesses.length)} note={`${pendingBusinesses.length} pending · ${hiddenBusinesses.length} hidden`}/><Metric title="Investors" value={String(investors.length)} note="Imported/public/private managed"/><Metric title="Profiles" value={String(profiles.length)} note={`${pendingProfiles.length} pending approval`}/><Metric title="Payments" value={String(payments.length)} note="Manual/Sepay beta"/><div className="dash card-wide"><h2>Release watch</h2><ul className="check-list"><li>Approve pending business profile changes before public exposure.</li><li>Keep investor private contact fields admin-only.</li><li>Confirm payments manually while webhook integration is Beta.</li></ul></div></div>}

  {tab==='businesses'&&<div>{filteredBusinesses.map(b=><BusinessEditor key={b.id} b={b} onSave={saveBusiness} onToggle={toggleBusiness} onApprove={approvePending}/>)}</div>}
  {tab==='business_review'&&<div><h2>Pending business review</h2>{pendingBusinesses.length?pendingBusinesses.map(b=><BusinessEditor key={b.id} b={b} onSave={saveBusiness} onToggle={toggleBusiness} onApprove={approvePending}/>):<div className="empty">No pending business changes.</div>}</div>}
  {tab==='investors'&&<div>{filteredInvestors.map(i=><InvestorEditor key={i.id} i={i} onSave={saveInvestor} onToggle={toggleInvestor}/>)}</div>}
  {tab==='investor_contacts'&&<div className="dash"><h2>Investor private contacts</h2><p className="notice warn">This tab is admin-only. Do not expose email, phone, website or real name on public/business pages unless connection and privacy rules allow.</p><table className="table"><thead><tr><th>Code</th><th>Private name</th><th>Email</th><th>Website</th><th>Phone</th><th>Visible</th></tr></thead><tbody>{filteredInvestors.slice(0,300).map(i=><tr key={i.id}><td>{i.code}</td><td>{i.private_name || '-'}</td><td>{i.private_email || '-'}</td><td>{i.private_website || '-'}</td><td>{i.private_phone || '-'}</td><td>{String(i.visible)}</td></tr>)}</tbody></table></div>}
  {tab==='payments'&&<div className="dash"><h2>Payments</h2><p className="muted">Sepay/QR webhook is Beta. Admin can confirm pending orders manually.</p><table className="table"><thead><tr><th>Order</th><th>Role</th><th>Amount</th><th>Status</th><th>Created</th><th>Action</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td>{p.order_ref || p.id}</td><td>{p.role || p.account_role || '-'}</td><td>{formatCompactMoney(p.amount,p.currency)}</td><td>{p.status}</td><td>{p.created_at ? new Date(p.created_at).toLocaleDateString() : '-'}</td><td><button className="btn small green" onClick={()=>markPayment(p,'paid')}>Mark paid</button> <button className="btn small secondary" onClick={()=>markPayment(p,'expired')}>Expire</button></td></tr>)}</tbody></table>{!payments.length&&<div className="empty">No payment orders yet.</div>}</div>}
  {tab==='promos'&&<div className="grid2"><form onSubmit={createPromo} className="dash formgrid"><h2 style={{gridColumn:'1/-1'}}>Create promo</h2><label>Code<input className="input" name="code" placeholder="FREE10JULY-DN16" required/></label><label>Role<select className="select" name="role"><option value="business">Business</option><option value="investor">Investor</option><option value="advisor">Advisor</option><option value="affiliate">Market Partner</option></select></label><label>Discount %<input className="input" name="discount_pct" type="number" defaultValue={100}/></label><label>Quota<input className="input" name="quota_total" type="number" defaultValue={16}/></label><label style={{gridColumn:'1/-1'}}>Description<input className="input" name="description" placeholder="Free launch promotion"/></label><label>Starts<input className="input" name="starts_at" type="datetime-local"/></label><label>Ends<input className="input" name="ends_at" type="datetime-local" defaultValue="2026-07-10T23:59"/></label><button className="btn">Create promo</button></form><div>{promos.map(p=><div className="card card-body" key={p.id}><b>{p.code}</b><p>{p.description}</p><div className="summary-row"><span>Role</span><b>{p.role === 'affiliate' ? 'Market Partner' : p.role}</b></div><div className="summary-row"><span>Discount</span><b>{p.discount_pct}%</b></div><div className="summary-row"><span>Quota</span><b>{p.quota_used || 0}/{p.quota_total || '-'}</b></div></div>)}</div></div>}
  {tab==='quality'&&<div>{criteria.map(c=><form onSubmit={e=>saveCriterion(e,c)} className="dash formgrid" key={c.id} style={{marginBottom:12}}><label>Label VI<input className="input" name="label_vi" defaultValue={c.label_vi}/></label><label>Label EN<input className="input" name="label_en" defaultValue={c.label_en}/></label><label>Weight<input className="input" name="weight" type="number" defaultValue={c.weight}/></label><label>Sort order<input className="input" name="sort_order" type="number" defaultValue={c.sort_order}/></label><label><input type="checkbox" name="active" defaultChecked={c.active}/> Active</label><button className="btn small">Save criterion</button></form>)}</div>}
  {tab==='requests'&&<div className="dash"><h2>Data requests</h2><table className="table"><thead><tr><th>Business</th><th>Investor</th><th>Items</th><th>Status</th><th>Action</th></tr></thead><tbody>{requests.map(r=><tr key={r.id}><td>{r.businesses?.public_code} · {r.businesses?.title_vi}</td><td>{r.investors?.code} · {r.investors?.title_en}</td><td>{(r.requested_items||[]).join(', ')}</td><td>{r.status}</td><td><button className="btn small" onClick={()=>markRequest(r,'forwarded')}>Forward</button> <button className="btn small green" onClick={()=>markRequest(r,'fulfilled')}>Fulfilled</button> <button className="btn small secondary" onClick={()=>markRequest(r,'declined')}>Decline</button></td></tr>)}</tbody></table></div>}
  {tab==='market_partners'&&<div className="dash"><h2>Market Partners</h2><p className="muted">Internal role remains <code>affiliate</code> for compatibility; UI label is Market Partner.</p><table className="table"><thead><tr><th>Name</th><th>Email</th><th>Status</th><th>Dashboard</th><th>Action</th></tr></thead><tbody>{marketPartners.map(p=><tr key={p.id}><td>{p.display_name || p.username}</td><td>{p.email}</td><td>{p.status}</td><td>{String(p.dashboard_login_enabled)}</td><td><button className="btn small green" onClick={()=>approveProfile(p)}>Approve</button> <button className="btn small secondary" onClick={()=>hideProfile(p)}>Hide</button></td></tr>)}</tbody></table>{!marketPartners.length&&<div className="empty">No Market Partner accounts yet.</div>}</div>}
  {tab==='logs'&&<div className="dash"><h2>Audit logs</h2><table className="table"><thead><tr><th>Time</th><th>Action</th><th>Entity</th><th>Detail</th></tr></thead><tbody>{logs.map(l=><tr key={l.id}><td>{new Date(l.created_at).toLocaleString()}</td><td>{l.action}</td><td>{l.entity_type}</td><td><code>{JSON.stringify(l.detail || {})}</code></td></tr>)}</tbody></table>{!logs.length&&<div className="empty">No audit logs yet.</div>}</div>}
  {tab==='settings'&&<div className="dash"><h2>Settings / feature flags</h2><p className="notice warn">Advanced settings, email queue, SEO and import automation are placeholders for later phases. The routes remain visible so QA can track release scope.</p><div className="kpis"><div className="kpi"><span>Market Partner label</span><b>Enabled</b></div><div className="kpi"><span>Internal role</span><b>affiliate</b></div><div className="kpi"><span>Public indexing</span><b>Review before deals68.com</b></div></div></div>}
  </main></div></section>
}

function filterRows(rows:any[], search:string, keys:string[]) { const q=search.trim().toLowerCase(); if(!q) return rows; return rows.filter(row=>keys.some(k=>String(row?.[k] || '').toLowerCase().includes(q))); }
function Metric({title,value,note}:{title:string;value:string;note:string}){ return <div className="dash metric-card"><span>{title}</span><b>{value}</b><p>{note}</p></div>; }
function BusinessEditor({b,onSave,onToggle,onApprove}:{b:any;onSave:(e:FormEvent,b:any)=>void;onToggle:(b:any)=>void;onApprove:(b:any)=>void}){ return <details className="card admin-editor" style={{marginBottom:12}}><summary className="card-body"><b>{b.public_code} · {b.company_name_private || b.title_vi}</b><span>{b.visible?'Visible':'Hidden'} · {b.status} · Quality {b.quality_score}/100 · {formatCompactMoney(b.revenue_2025,b.revenue_currency)}</span></summary><div className="card-body"><form onSubmit={(e)=>onSave(e,b)} className="formgrid"><label style={{gridColumn:'1/-1'}}>Title VI<input className="input" name="title_vi" defaultValue={b.title_vi}/></label><label>Industry<input className="input" name="industry" defaultValue={b.industry}/></label><label>Deal type<input className="input" name="deal_type" defaultValue={b.deal_type}/></label><label>Revenue 2025<input className="input" name="revenue_2025" type="number" defaultValue={b.revenue_2025}/></label><label>EBITDA %<input className="input" name="ebitda_margin" type="number" defaultValue={b.ebitda_margin}/></label><label>Ask<input className="input" name="ask_amount" type="number" defaultValue={b.ask_amount}/></label><label>Stake %<input className="input" name="stake_pct" type="number" defaultValue={b.stake_pct}/></label><label>Quality Score<input className="input" name="quality_score" type="number" defaultValue={b.quality_score}/></label><label>Data Confidence<input className="input" name="data_confidence" type="number" defaultValue={b.data_confidence}/></label><label>Plan<select className="select" name="plan" defaultValue={b.plan}><option value="standard">standard</option><option value="featured">featured</option><option value="priority">priority</option></select></label><label>Status<select className="select" name="status" defaultValue={b.status}><option value="active">active</option><option value="pending_admin_review">pending_admin_review</option><option value="hidden">hidden</option><option value="expired">expired</option></select></label><label><input type="checkbox" name="visible" defaultChecked={!!b.visible}/> Visible public</label><button className="btn">Save business</button><button type="button" className="btn secondary" onClick={()=>onToggle(b)}>{b.visible?'Hide':'Show'}</button>{b.pending_changes_json&&<button type="button" className="btn green" onClick={()=>onApprove(b)}>Approve pending</button>}</form>{b.pending_changes_json&&<pre className="json-preview">{JSON.stringify(b.pending_changes_json,null,2)}</pre>}</div></details>; }
function InvestorEditor({i,onSave,onToggle}:{i:any;onSave:(e:FormEvent,i:any)=>void;onToggle:(i:any)=>void}){ return <details className="card admin-editor" style={{marginBottom:12}}><summary className="card-body"><b>{i.code} · {i.private_name || i.title_en}</b><span>{i.type} · {i.visible?'Visible':'Hidden'} · {i.private_email || 'no email'}</span></summary><div className="card-body"><form onSubmit={e=>onSave(e,i)} className="formgrid"><label>Title EN<input className="input" name="title_en" defaultValue={i.title_en}/></label><label>Title VI<input className="input" name="title_vi" defaultValue={i.title_vi}/></label><label>Type<input className="input" name="type" defaultValue={i.type}/></label><label>Country<input className="input" name="country" defaultValue={i.country}/></label><label>Country ISO2<input className="input" name="country_iso2" defaultValue={i.country_iso2}/></label><label>Industries<input className="input" name="industries" defaultValue={(i.industries||[]).join(', ')}/></label><label>Deal types<input className="input" name="deal_types" defaultValue={(i.deal_types||[]).join(', ')}/></label><label>Ticket min<input className="input" name="ticket_min" type="number" defaultValue={i.ticket_min}/></label><label>Ticket max<input className="input" name="ticket_max" type="number" defaultValue={i.ticket_max}/></label><label>Private name<input className="input" name="private_name" defaultValue={i.private_name}/></label><label>Private website<input className="input" name="private_website" defaultValue={i.private_website}/></label><label>Private email<input className="input" name="private_email" defaultValue={i.private_email}/></label><label>Private phone<input className="input" name="private_phone" defaultValue={i.private_phone}/></label><label><input type="checkbox" name="verified" defaultChecked={!!i.verified}/> Verified</label><label><input type="checkbox" name="admin_priority" defaultChecked={!!i.admin_priority}/> Admin priority</label><label style={{gridColumn:'1/-1'}}>Description EN<textarea className="textarea" name="desc_en" defaultValue={i.desc_en}/></label><button className="btn">Save investor</button><button type="button" className="btn secondary" onClick={()=>onToggle(i)}>{i.visible?'Hide':'Show'}</button></form></div></details>; }
