import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { getBusinessBySlug, getInvestorByOwner } from '../lib/data';
import { formatCompactMoney, formatMoney, percent } from '../lib/format';
import { useAuth } from '../contexts/AuthContext';
import type { Lang } from '../lib/i18n';
import { t } from '../lib/i18n';

const criteriaNames = ['Profile completeness','Financial data quality','Data source confidence','Deal terms clarity','Documents & data room','Valuation rationale','Growth & margin','Admin reviewed'];
export default function BusinessDetail({ lang }: { lang: Lang }){
  const { slug }=useParams(); const { profile }=useAuth(); const navigate=useNavigate();
  const [b,setB]=useState<any>(); const [investor,setInvestor]=useState<any>(); const [msg,setMsg]=useState(''); const isInvestor=profile?.role==='investor';
  useEffect(()=>{ if(slug) getBusinessBySlug(slug).then(setB); },[slug]);
  useEffect(()=>{ if(profile?.role==='investor') getInvestorByOwner(profile.id).then(setInvestor).catch(()=>{}); },[profile?.id]);
  async function expressInterest(){ if(!profile){ navigate('/login?next='+location.pathname); return;} if(profile.role!=='investor'||!investor){setMsg('Only investor accounts can express interest.');return;} const {error}=await supabase.from('investor_interests').upsert({business_id:b.id,investor_id:investor.id,status:'interested'},{onConflict:'business_id,investor_id'}); setMsg(error?error.message:'Interest submitted. Business can approve the connection from dashboard.'); }
  async function save(){ if(!profile){navigate('/login?next='+location.pathname);return;} if(!investor){setMsg('Investor profile not found.');return;} const {error}=await supabase.from('saved_businesses').upsert({business_id:b.id,investor_id:investor.id},{onConflict:'investor_id,business_id'}); setMsg(error?error.message:'Saved to your dashboard.'); }
  async function requestData(){ if(!profile){navigate('/login?next='+location.pathname);return;} if(!investor){setMsg('Investor profile not found.');return;} const {error}=await supabase.from('request_data').insert({business_id:b.id,investor_id:investor.id,requested_items:['IM','NDA','Financial statements'],note:'Investor requested IM/NDA from business detail.'}); setMsg(error?error.message:'Request sent to Deals68/admin and business dashboard.'); }
  if(!b) return <section className="section"><div className="container empty">Loading...</div></section>;
  return <><section className="detail-hero"><div className="container detail-grid"><div><span className="pill gold">{b.public_code}</span><span className="pill green">{b.plan}</span><h1>{lang==='en'?b.title_en:b.title_vi}</h1><p className="muted">{b.industry} · {b.city || b.country_iso2}</p></div><div className="card"><div className="card-body"><b>Transaction</b><div className="kpis"><div className="kpi"><span>2025 Revenue</span><b>{formatCompactMoney(b.revenue_2025,b.revenue_currency)}</b></div><div className="kpi"><span>EBITDA</span><b>{percent(b.ebitda_margin)}</b></div><div className="kpi"><span>Ask / Stake</span><b>{formatCompactMoney(b.ask_amount,b.ask_currency)} / {percent(b.stake_pct)}</b></div></div><button className="btn" onClick={expressInterest}>{t(lang,'expressInterest')}</button> <button className="btn secondary" onClick={save}>{t(lang,'save')}</button><div style={{height:8}}/><button className="btn secondary" onClick={requestData}>{t(lang,'requestData')} IM/NDA</button>{msg&&<p className="notice">{msg}</p>}</div></div></div></section><section className="section"><div className="container detail-grid"><div><img className="deal-img" style={{height:360,borderRadius:22}} src={b.image_url || '/assets/deal1.svg'} alt="deal"/><div className="card" style={{marginTop:18}}><div className="card-body"><h2>{lang==='en'?'Highlights':'Điểm nổi bật'}</h2><p style={{whiteSpace:'pre-line'}}>{lang==='en'?b.highlights_en:b.highlights_vi}</p><h2>{lang==='en'?'Use of funds / sale reason':'Lý do gọi vốn / bán'}</h2><p>{lang==='en'?b.investment_reason_en:b.investment_reason_vi}</p></div></div></div><aside><div className="card"><div className="card-body"><h3>{t(lang,'businessQuality')}: {b.quality_score}/100</h3><div className="score"><span style={{width:`${b.quality_score}%`}}/></div>{isInvestor ? <div style={{marginTop:12}}>{criteriaNames.map((c,i)=><div key={c} style={{display:'flex',justifyContent:'space-between',borderBottom:'1px solid #e2e8f0',padding:'8px 0'}}><span>{c}</span><b>{Math.max(50,Math.min(95,Number(b.quality_score)+((i%3)-1)*5))}/100</b></div>)}</div> : <div style={{marginTop:12}}><p className="notice warn">{t(lang,'onlyInvestorsQuality')}</p><ul>{criteriaNames.map(c=><li key={c}>{c}</li>)}</ul></div>}</div></div><div className="card" style={{marginTop:18}}><div className="card-body"><h3>Locked data room</h3><p className="muted">Financial files, IM/NDA and contact details unlock only after proposal/connection approval.</p><Link className="btn secondary" to="/pricing">Upgrade / register</Link></div></div></aside></div></section></>
}
