import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { getInvestorByCode } from '../lib/data';
import { formatCompactMoney } from '../lib/format';
import { useAuth } from '../contexts/AuthContext';
import { toLocalizedPath } from '../lib/i18nRoutes';
import type { Lang } from '../lib/i18n';

const T = (lang: Lang, vi: string, en: string) => lang === 'en' ? en : vi;
function arr(v: any): string[] { if (Array.isArray(v)) return v.filter(Boolean).map(String); if (!v) return []; return String(v).split(/[;,]/).map((x) => x.trim()).filter(Boolean); }
function ticket(min: any, max: any) { const a = Number(min || 0), b = Number(max || 0); if (!a && !b) return 'TBD'; return `${formatCompactMoney(a, 'USD')} – ${formatCompactMoney(b, 'USD')}`; }
function criteriaList(criteria: any): string[] { if (!criteria || typeof criteria !== 'object') return []; return Object.entries(criteria).map(([k, v]) => `${k.replace(/_/g, ' ')}: ${Array.isArray(v) ? v.join(', ') : String(v ?? '')}`).filter((x) => !x.endsWith(': ')); }

export default function InvestorDetail({ lang }: { lang: Lang }) {
  const { code = '' } = useParams(); const { profile } = useAuth(); const navigate = useNavigate();
  const [inv, setInv] = useState<any>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [msg, setMsg] = useState('');
  useEffect(() => { let live = true; async function load() { setLoading(true); setError(''); setInv(null); try { const data = await getInvestorByCode(code); if (!live) return; if (!data) setError(T(lang, 'Không tìm thấy hồ sơ nhà đầu tư hoặc hồ sơ chưa public.', 'Investor profile not found or not public.')); else setInv(data); } catch (e: any) { if (live) setError(e?.message || T(lang, 'Không tải được hồ sơ nhà đầu tư.', 'Could not load investor profile.')); } finally { if (live) setLoading(false); } } load(); return () => { live = false; }; }, [code, lang]);
  const title = inv ? T(lang, inv.title_vi || inv.code || 'Nhà đầu tư', inv.title_en || inv.title_vi || inv.code || 'Investor') : '';
  const industries = useMemo(() => arr(inv?.industries), [inv]); const dealTypes = useMemo(() => arr(inv?.deal_types), [inv]); const criteria = useMemo(() => criteriaList(inv?.criteria), [inv]);
  const facts = inv ? [[T(lang, 'Mã hồ sơ', 'Profile code'), inv.code || '-'], [T(lang, 'Loại nhà đầu tư', 'Investor type'), inv.type || 'Investor'], [T(lang, 'Quốc gia', 'Country'), inv.country || inv.country_iso2 || 'Global'], [T(lang, 'Khu vực', 'Region'), inv.region || 'Global'], ['Ticket', ticket(inv.ticket_min, inv.ticket_max)], [T(lang, 'Ngành quan tâm', 'Preferred industries'), industries.join(', ') || 'TBD'], [T(lang, 'Loại giao dịch', 'Deal types'), dealTypes.join(', ') || 'TBD'], [T(lang, 'Giai đoạn', 'Stage'), inv.stage || 'TBD'], [T(lang, 'Trạng thái xác minh', 'Verification status'), inv.verified === true ? T(lang, 'Đã xác minh', 'Verified') : T(lang, 'Chờ xác nhận', 'Pending')]] : [];
  function sendProposal() { if (!profile) { navigate(toLocalizedPath('/register/business', lang)); return; } if (profile.role !== 'business') { setMsg(T(lang, 'Chỉ tài khoản Doanh nghiệp được gửi proposal.', 'Only Business accounts can send proposals.')); return; } setMsg(T(lang, 'Vui lòng gửi proposal từ Business Dashboard để hệ thống ghi nhận hạn mức/quota và workflow duyệt.', 'Please send proposals from the Business Dashboard so quota and approval workflow are recorded.')); }
  if (loading) return <main className="d68-investor-detail"><div className="d68-id-state">{T(lang, 'Đang tải hồ sơ thật từ database...', 'Loading live investor profile from database...')}</div></main>;
  if (error || !inv) return <main className="d68-investor-detail"><div className="d68-id-state"><h1>{T(lang, 'Không hiển thị được hồ sơ', 'Profile unavailable')}</h1><p>{error}</p><Link to={toLocalizedPath('/investors', lang)}>← {T(lang, 'Quay lại danh sách', 'Back to investors')}</Link></div></main>;
  return <main className="d68-investor-detail"><section className="d68-id-wrap"><div className="d68-id-breadcrumb"><Link to={toLocalizedPath('/', lang)}>{T(lang, 'Trang chủ', 'Home')}</Link> › <Link to={toLocalizedPath('/investors', lang)}>{T(lang, 'Nhà đầu tư', 'Investors')}</Link> › <b>{inv.code}</b></div><div className="d68-id-cols"><article className="d68-id-main"><div className="d68-id-badges"><span>{inv.type || 'Investor'}</span>{inv.verified ? <span className="verified">✓ {T(lang, 'Xác minh', 'Verified')}</span> : null}</div><h1>{title}</h1><p>{T(lang, inv.desc_vi || 'Hồ sơ ẩn danh đang được cập nhật tiêu chí đầu tư.', inv.desc_en || inv.desc_vi || 'Anonymous investor profile is being updated.')}</p><Section title={T(lang, 'Thông tin chính', 'Key facts')}><div className="d68-id-facts">{facts.map(([k, v]) => <Fact key={k} k={k} v={v} />)}</div></Section><Section title={T(lang, 'Tiêu chí đầu tư từ database', 'Database-backed investment criteria')}><ul>{criteria.length ? criteria.map((x, i) => <li key={i}>{x}</li>) : <li>{T(lang, 'Chưa có tiêu chí chi tiết.', 'No detailed criteria yet.')}</li>}</ul></Section><Section title={T(lang, 'Quyền xem thông tin', 'Information access')}><p>{T(lang, 'Tên thật, email, số điện thoại, website và thông tin liên hệ riêng tư không hiển thị công khai. Những thông tin này chỉ được mở theo workflow duyệt kết nối và tùy chọn riêng tư của nhà đầu tư.', 'Real name, email, phone, website and private contact details are not public. They unlock only through approved connection workflow and investor privacy settings.')}</p></Section></article><aside className="d68-id-side"><div className="d68-id-cta"><span>{T(lang, 'Gửi proposal', 'Send proposal')}</span><h2>{ticket(inv.ticket_min, inv.ticket_max)}</h2><p>{industries.join(', ') || 'Industries TBD'}</p><button onClick={sendProposal}>{T(lang, 'Gửi hồ sơ DN', 'Send business profile')}</button></div><div className="d68-id-locked"><h3>{T(lang, 'Thông tin liên hệ bị khóa', 'Contact details locked')}</h3><p>🔒 Email · Phone · Website</p><small>{T(lang, 'Chỉ mở sau workflow kết nối được duyệt.', 'Unlocked only after approved connection workflow.')}</small></div><div className="d68-id-note"><h3>{T(lang, 'Dữ liệu trung thực', 'Data integrity')}</h3><p>{T(lang, 'Trang này không dùng lịch sử proposal, biểu đồ hay tiêu chí giả khi database chưa có dữ liệu backing.', 'This page does not use fake proposal history, charts or criteria when database backing data is missing.')}</p></div>{msg ? <div className="d68-id-msg">{msg}</div> : null}</aside></div></section></main>;
}
function Section({ title, children }: { title: string; children: any }) { return <section className="d68-id-section"><h2>{title}</h2>{children}</section>; }
function Fact({ k, v }: { k: string; v: string }) { return <div className="d68-id-fact"><span>{k}</span><b>{v}</b></div>; }
