import { FormEvent, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { createBusinessFromProfile, createInvestorForOwner } from '../lib/data';
import { slugify } from '../lib/format';
import { autoEnglishFromVietnamese } from '../lib/i18n';
import type { Role } from '../lib/supabase';

export default function Register(){ const {role='business'}=useParams(); const r=(role === 'market-partner' ? 'affiliate' : role) as Role; const displayRole = role === 'market-partner' || r === 'affiliate' ? 'market-partner' : r; const {signUp}=useAuth(); const navigate=useNavigate(); const intent=useMemo(()=>{try{return JSON.parse(localStorage.getItem('d68_checkout_intent')||'{}')}catch{return{}}},[]); const [plan,setPlan]=useState('standard'); const [email,setEmail]=useState(''); const [password,setPassword]=useState('deals68User68!'); const [name,setName]=useState(''); const [titleVi,setTitleVi]=useState(''); const [industry,setIndustry]=useState(''); const [country,setCountry]=useState(intent.country||'VN'); const [revenue,setRevenue]=useState(''); const [ebitda,setEbitda]=useState(''); const [ask,setAsk]=useState(''); const [stake,setStake]=useState(''); const [promo,setPromo]=useState(''); const [msg,setMsg]=useState(''); async function submit(e:FormEvent){e.preventDefault(); const username=(email.split('@')[0]||slugify(name)).toLowerCase().replace(/[^a-z0-9._-]/g,''); const sr=await signUp(r,email,password,{username,display_name:name,country_iso2:country}); if(sr.error||!sr.user){setMsg(sr.error||'Cannot create account');return;} if(r==='business'){ await createBusinessFromProfile(sr.user.id,{ username, slug:slugify(titleVi||name)+'-'+Date.now().toString(36), public_code:'D68-NEW', company_name_private:name, title_vi:titleVi, title_en:autoEnglishFromVietnamese(titleVi), country_iso2:country, city:'', industry, deal_type:'Fundraise', plan, revenue_2025:Number(revenue||0), revenue_currency:'VND', ebitda_margin:Number(ebitda||0), ask_amount:Number(ask||0), ask_currency:'VND', stake_pct:Number(stake||0), quota_total:plan==='featured'?200:100, highlights_vi:'', highlights_en:'', investment_reason_vi:'', investment_reason_en:'' }); }
      if(r==='investor'){ await createInvestorForOwner(sr.user.id,{ code:'INV-NEW-'+Date.now().toString(36), username, title_vi:`Nhà đầu tư quan tâm ${industry||'doanh nghiệp Việt Nam'}`, title_en:`Investor interested in ${industry||'Vietnam businesses'}`, country_iso2:country, country, industries:industry?[industry]:[], ticket_min:0, ticket_max:5000000, type:'Individual/Angel', criteria:{revenueRange:'', ebitdaRange:'', sectors:industry?[industry]:[]}, privacy:{shareEmail:false,email,sharePhone:false,phone:'',phoneCountry:'VN'} }); }
      setMsg('Account created. Please complete QR payment/admin approval.'); setTimeout(()=>navigate('/login'),1200); }
  return <section className="section"><div className="container" style={{maxWidth:780}}><div className="card"><div className="card-body"><h1>{r==='business'?'Tạo tài khoản Doanh nghiệp':r==='investor'?'Create Investor Account':displayRole==='market-partner'?'Register Market Partner':'Advisor Waitlist'}</h1>{intent.role&&<p className="notice">Đã lấy lựa chọn từ Pricing: role {intent.role}, kỳ hạn {intent.termWeeks||1} tuần.</p>}<form onSubmit={submit} className="formgrid"><label>Account email<input className="input" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input className="input" required type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Name / Company<input className="input" required value={name} onChange={e=>setName(e.target.value)}/></label><label>Country<select className="select" value={country} onChange={e=>setCountry(e.target.value)}><option value="VN">Vietnam</option><option value="SG">Singapore</option><option value="US">United States</option><option value="JP">Japan</option><option value="KR">Korea</option><option value="CN">China</option></select></label>{r==='business'&&<><label>Gói dịch vụ<select className="select" value={plan} onChange={e=>setPlan(e.target.value)}><option value="standard">Thường - 500.000đ/tuần - 100 proposals</option><option value="featured">Ưu tiên - 650.000đ/tuần - 200 proposals</option></select></label><label>Promo code<input className="input" value={promo} onChange={e=>setPromo(e.target.value)} placeholder="vd FREE10JULY"/></label><label style={{gridColumn:'1/-1'}}>Tiêu đề hồ sơ DN<input className="input" required value={titleVi} onChange={e=>setTitleVi(e.target.value)}/></label><label>Lĩnh vực<input className="input" value={industry} onChange={e=>setIndustry(e.target.value)}/></label><label>Doanh thu 2025<input className="input" type="number" value={revenue} onChange={e=>setRevenue(e.target.value)}/></label><label>EBITDA %<input className="input" type="number" value={ebitda} onChange={e=>setEbitda(e.target.value)}/></label><label>Số tiền gọi vốn/giá chào<input className="input" type="number" value={ask} onChange={e=>setAsk(e.target.value)}/></label><label>% cổ phần<input className="input" type="number" value={stake} onChange={e=>setStake(e.target.value)}/></label></>}{r==='investor'&&<label style={{gridColumn:'1/-1'}}>Investment sectors<input className="input" value={industry} onChange={e=>setIndustry(e.target.value)} placeholder="IT & Software"/></label>}<div style={{gridColumn:'1/-1'}}><button className="btn" type="submit">Create account</button>{msg&&<p className="notice">{msg}</p>}</div></form></div></div></div></section> }
