import { FormEvent, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { toLocalizedPath } from '../lib/i18nRoutes';
import type { Lang } from '../lib/i18n';
const T = (lang: Lang, vi: string, en: string) => lang === 'en' ? en : vi;
export default function ResetPassword({ lang = 'vi' }: { lang?: Lang }) {
  const navigate = useNavigate(); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [msg, setMsg] = useState(''); const [err, setErr] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); setErr(''); setMsg(''); if (password.length < 8) { setErr(T(lang,'Mật khẩu cần tối thiểu 8 ký tự.','Password must be at least 8 characters.')); return; } if (password !== confirm) { setErr(T(lang,'Mật khẩu xác nhận không khớp.','Password confirmation does not match.')); return; } setLoading(true); const { error } = await supabase.auth.updateUser({ password }); setLoading(false); if (error) setErr(error.message); else { setMsg(T(lang,'Đã cập nhật mật khẩu. Đang chuyển về đăng nhập...','Password updated. Redirecting to login...')); setTimeout(()=>navigate(toLocalizedPath('/login', lang)), 900); } }
  return <main className="d68-auth-page"><section className="d68-auth-card"><div className="d68-auth-head"><span>Deals68</span><h1>{T(lang,'Đặt lại mật khẩu','Reset password')}</h1><p>{T(lang,'Nhập mật khẩu mới sau khi mở link từ email.','Enter a new password after opening the email link.')}</p></div><form onSubmit={submit} className="d68-auth-form"><label><span>{T(lang,'Mật khẩu mới','New password')}</span><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} /></label><label><span>{T(lang,'Xác nhận mật khẩu','Confirm password')}</span><input required type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} /></label><button className="d68-auth-submit" disabled={loading}>{loading ? T(lang,'Đang cập nhật...','Updating...') : T(lang,'Cập nhật mật khẩu','Update password')}</button>{msg&&<div className="d68-auth-success">{msg}</div>}{err&&<div className="d68-auth-error">{err}</div>}</form><p className="d68-auth-bottom"><Link to={toLocalizedPath('/login', lang)}>{T(lang,'Đăng nhập','Log in')}</Link></p></section></main>;
}
