import { FormEvent, useState } from 'react';
import { Link } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import type { Lang } from '../lib/i18n';

const T = (lang: Lang, vi: string, en: string) => lang === 'en' ? en : vi;
type Props = { lang: Lang };
const input = { border: '1px solid #E2E8F0', borderRadius: 10, padding: '12px 13px', fontSize: 15, color: '#0F2A4A', background: '#fff', width: '100%' };

function Hero({ lang, kicker, kickerEn, title, titleEn, desc, descEn }: Props & { kicker: string; kickerEn: string; title: string; titleEn: string; desc: string; descEn: string }) {
  return <section style={{ background: '#F7FAFC', borderBottom: '1px solid #E7EDF3' }}><div style={{ maxWidth: 920, margin: '0 auto', padding: '58px 24px 48px', textAlign: 'center' }}><div style={{ display: 'inline-flex', background: '#E7F6FD', color: '#1596cc', fontWeight: 800, fontSize: 12, padding: '6px 12px', borderRadius: 999, marginBottom: 14, textTransform: 'uppercase' }}>{T(lang, kicker, kickerEn)}</div><h1 style={{ fontSize: 38, margin: '0 0 14px', letterSpacing: -.8 }}>{T(lang, title, titleEn)}</h1><p style={{ color: '#64748B', lineHeight: 1.65, fontSize: 16, margin: '0 auto', maxWidth: 720 }}>{T(lang, desc, descEn)}</p></div></section>;
}
function CTA({ lang, to, title, titleEn, cta, ctaEn }: Props & { to: string; title: string; titleEn: string; cta: string; ctaEn: string }) { return <div style={{ background: '#0F2A4A', color: '#fff', borderRadius: 18, padding: 28, marginTop: 28, display: 'flex', justifyContent: 'space-between', gap: 18, alignItems: 'center', flexWrap: 'wrap' }}><h2 style={{ margin: 0 }}>{T(lang, title, titleEn)}</h2>{to.startsWith('mailto:') ? <a href={to} style={{ background: '#F2B51D', color: '#0F2A4A', fontWeight: 800, padding: '12px 20px', borderRadius: 10 }}>{T(lang, cta, ctaEn)} →</a> : <Link to={to} style={{ background: '#F2B51D', color: '#0F2A4A', fontWeight: 800, padding: '12px 20px', borderRadius: 10 }}>{T(lang, cta, ctaEn)} →</Link>}</div>; }
function Card({ icon, title, children }: { icon: string; title: string; children: any }) { return <div style={{ background: '#fff', border: '1px solid #E7EDF3', borderRadius: 16, padding: 24 }}><div style={{ width: 44, height: 44, borderRadius: 12, background: '#EAF0F6', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 21, marginBottom: 14 }}>{icon}</div><h3 style={{ margin: '0 0 8px' }}>{title}</h3><div style={{ color: '#64748B', lineHeight: 1.6 }}>{children}</div></div>; }
function Section({ children, narrow=false }: { children: any; narrow?: boolean }) { return <section style={{ maxWidth: narrow ? 860 : 1120, margin: '0 auto', padding: '58px 24px' }}>{children}</section>; }

export function About({ lang }: Props) {
  return <><Hero lang={lang} kicker="Giới thiệu" kickerEn="About" title="Về Deals68" titleEn="About Deals68" desc="Deals68.com là nền tảng kết nối cơ hội mua bán doanh nghiệp, sang nhượng cửa hàng, đầu tư, vay vốn và cho vay dành cho doanh nghiệp Việt toàn cầu, nhà đầu tư toàn cầu và các đối tác vốn quốc tế." descEn="Deals68.com connects business acquisition, store transfer, investment, lending and private capital opportunities for global Vietnamese businesses, international investors and capital partners."/><Section><div style={{ textAlign: 'center', maxWidth: 760, margin: '0 auto 34px' }}><h2>{T(lang, 'Tầm nhìn toàn cầu của Deals68', 'Deals68 global vision')}</h2><p style={{ color: '#64748B', lineHeight: 1.7 }}>{T(lang, 'Giai đoạn đầu, Deals68 tập trung phục vụ doanh nghiệp Việt Nam, chủ cửa hàng, nhà đầu tư người Việt ở nước ngoài và các đối tác vốn quan tâm đến doanh nghiệp Việt. Sau đó, nền tảng sẽ từng bước mở rộng sang doanh nghiệp và nhà đầu tư quốc tế ở nhiều thị trường.', 'In the first stage, Deals68 focuses on Vietnamese businesses, store owners, overseas Vietnamese investors and capital partners interested in Vietnam-related opportunities. Over time, the platform will expand to international businesses and investors across multiple markets.')}</p></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 18 }} className="d68-form-2"><Card icon="🎯" title={T(lang, 'Mục tiêu ba năm', '3-Year Goal')}><b style={{ fontSize: 28, color: '#0F2A4A' }}>300.000 – 500.000</b><p>{T(lang, 'Doanh nghiệp, chủ cửa hàng, nhà đầu tư, người mua, bên cho vay và đối tác vốn Việt Nam - quốc tế.', 'Businesses, store owners, investors, buyers, lenders and capital partners across Vietnamese and international markets.')}</p></Card><Card icon="🌍" title={T(lang, 'Mục tiêu năm năm', '5-Year Goal')}><b style={{ fontSize: 28, color: '#0F2A4A' }}>{T(lang, 'Tối thiểu 1 triệu', '1 million+')}</b><p>{T(lang, 'Doanh nghiệp và nhà đầu tư toàn cầu.', 'Businesses and investors globally.')}</p></Card></div><CTA lang={lang} to="/businesses" title="Khám phá cơ hội trên Deals68" titleEn="Explore opportunities on Deals68" cta="Xem doanh nghiệp" ctaEn="View businesses" /></Section></>;
}

const terms = [
  ['Vai trò của Deals68', 'Role of Deals68', 'Deals68 là nền tảng hỗ trợ hiển thị, sàng lọc, chuẩn hóa thông tin ban đầu và kết nối các bên có nhu cầu phù hợp. Deals68 không cam kết thương vụ thành công.', 'Deals68 supports presentation, screening, initial standardisation and connection between relevant parties. Deals68 does not guarantee deal completion.'],
  ['Không phải tư vấn đầu tư', 'No investment advice', 'Thông tin trên Deals68 chỉ nhằm mục đích tham khảo và sàng lọc ban đầu. Người dùng cần tự thẩm định và chịu trách nhiệm cho quyết định của mình.', 'Information on Deals68 is for reference and initial screening only. Users should conduct their own due diligence and take responsibility for their decisions.'],
  ['Nghĩa vụ của người dùng', 'User obligations', 'Người dùng phải cung cấp thông tin trung thực, hợp pháp và có quyền chia sẻ; không đăng nội dung gây hiểu lầm hoặc xâm phạm quyền của bên thứ ba.', 'Users must provide accurate, lawful information they are entitled to share, and must not post misleading content or infringe third-party rights.'],
  ['Dữ liệu và tài liệu', 'Data and documents', 'Tài liệu nhạy cảm chỉ được mở theo quy trình kết nối được duyệt. Deals68 có thể yêu cầu bổ sung hoặc chỉnh sửa dữ liệu trước khi công khai.', 'Sensitive documents unlock only through an approved connection process. Deals68 may request additions or corrections before publication.']
];
export function Terms({ lang }: Props) { return <><Hero lang={lang} kicker="Điều khoản" kickerEn="Terms" title="Điều khoản sử dụng" titleEn="Terms of Use" desc="Bằng việc sử dụng nền tảng, người dùng xác nhận đã đọc, hiểu và đồng ý tuân thủ các điều khoản dưới đây." descEn="By using the platform, users confirm that they have read, understood and agree to these terms."/><Section narrow><Notice lang={lang}/><LegalList lang={lang} items={terms}/></Section></>; }
const privacy = [
  ['Hồ sơ ẩn danh', 'Anonymous profiles', 'Tên pháp lý, thông tin liên hệ, tài liệu tài chính và dữ liệu nhạy cảm không hiển thị công khai.', 'Legal names, contact details, financial documents and sensitive data are not displayed publicly.'],
  ['Mở khóa thông tin', 'Information unlock', 'Thông tin liên hệ và tài liệu chỉ mở sau khi có đề xuất hoặc kết nối được duyệt theo quy trình của Deals68.', 'Contact information and documents unlock only after an approved proposal or connection under Deals68 workflow.'],
  ['Quyền của người dùng', 'User rights', 'Người dùng có thể yêu cầu xem, chỉnh sửa, cập nhật, ẩn hoặc xóa thông tin cá nhân của mình.', 'Users may request to view, edit, update, hide or delete their personal information.']
];
export function Privacy({ lang }: Props) { return <><Hero lang={lang} kicker="Bảo mật" kickerEn="Privacy" title="Chính sách bảo mật" titleEn="Privacy Policy" desc="Deals68 ưu tiên hồ sơ ẩn danh, kiểm soát quyền xem và chỉ mở thông tin nhạy cảm khi có kết nối được duyệt." descEn="Deals68 prioritises anonymous profiles, access control and unlocking sensitive information only after approved connections."/><Section narrow><LegalList lang={lang} items={privacy}/><CTA lang={lang} to="/contact" title="Câu hỏi về dữ liệu riêng tư?" titleEn="Questions about privacy?" cta="Liên hệ" ctaEn="Contact us" /></Section></>; }
function LegalList({ lang, items }: Props & { items: string[][] }) { return <div style={{ display: 'flex', flexDirection: 'column', gap: 26 }}>{items.map((it, i) => <div id={`sec-${i+1}`} key={it[0]} style={{ background: '#fff', border: '1px solid #E7EDF3', borderRadius: 16, padding: 24 }}><h2 style={{ margin: '0 0 10px' }}>{T(lang, it[0], it[1])}</h2><p style={{ color: '#334155', lineHeight: 1.7, margin: 0 }}>{T(lang, it[2], it[3])}</p></div>)}</div>; }
function Notice({ lang }: Props) { return <div style={{ display: 'flex', gap: 12, background: '#FEF3D3', border: '1px solid #F5DFA0', borderRadius: 14, padding: 18, marginBottom: 28, color: '#7a5c12', fontWeight: 600 }}>⚠️ <span>{T(lang, 'Thông tin trên Deals68 không phải là lời khuyên đầu tư, pháp lý, thuế hoặc tín dụng.', 'Information on Deals68 is not investment, legal, tax or credit advice.')}</span></div>; }

export function Contact({ lang }: Props) {
  const [form, setForm] = useState({ name: '', email: '', message: '' });
  const [status, setStatus] = useState<{ ok?: boolean; msg: string } | null>(null);
  async function submit(e: FormEvent) {
    e.preventDefault(); setStatus(null);
    if (!form.name.trim() || !form.email.trim() || !form.message.trim()) { setStatus({ ok: false, msg: T(lang, 'Vui lòng nhập đầy đủ thông tin.', 'Please complete all fields.') }); return; }
    const { error } = await supabase.from('contact_messages').insert({ name: form.name.trim(), email: form.email.trim(), message: form.message.trim(), source: 'contact_page', status: 'new' });
    if (error) setStatus({ ok: false, msg: T(lang, `Chưa lưu được tin nhắn: ${error.message}`, `Message was not saved: ${error.message}`) });
    else { setStatus({ ok: true, msg: T(lang, 'Đã lưu tin nhắn. Deals68 sẽ phản hồi qua email.', 'Message saved. Deals68 will respond by email.') }); setForm({ name: '', email: '', message: '' }); }
  }
  return <><Hero lang={lang} kicker="Liên hệ" kickerEn="Contact" title="Liên hệ" titleEn="Contact" desc="Có câu hỏi, góp ý hoặc muốn hợp tác với Deals68? Gửi lời nhắn cho chúng tôi." descEn="Have a question, feedback or partnership idea for Deals68? Send us a message."/><Section><div style={{ display: 'grid', gridTemplateColumns: '1.25fr .9fr', gap: 30 }} className="d68-form-2"><form onSubmit={submit} style={{ background: '#fff', border: '1px solid #E7EDF3', borderRadius: 18, padding: 30 }}><h2>{T(lang, 'Gửi lời nhắn cho chúng tôi', 'Send us a message')}</h2><div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}><input style={input} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder={T(lang, 'Họ và tên', 'Full name')} /><input style={input} value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="email@example.com" type="email" /><textarea style={{ ...input, minHeight: 140 }} value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} placeholder={T(lang, 'Nội dung liên hệ / góp ý', 'Message / feedback')} /><button style={{ background: '#0F2A4A', color: '#fff', fontWeight: 800, border: 'none', borderRadius: 11, padding: 14 }}>{T(lang, 'Gửi liên hệ', 'Send message')}</button>{status ? <div style={{ padding: 12, borderRadius: 10, background: status.ok ? '#E9F9EF' : '#FDECEC', color: status.ok ? '#16A34A' : '#DC2626', fontWeight: 700 }}>{status.msg}</div> : null}</div></form><div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}><Card icon="✉️" title="Email"><a href="mailto:partner@vietcapitalpartners.com">partner@vietcapitalpartners.com</a><p>Hotline/Zalo: 0909.584.075</p></Card><Card icon="🚀" title={T(lang, 'Lối tắt', 'Shortcuts')}><div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}><Link to="/register/business">{T(lang, 'Đăng hồ sơ doanh nghiệp', 'Register a business')}</Link><Link to="/register/investor">{T(lang, 'Đăng ký nhà đầu tư', 'Register as investor')}</Link><Link to="/partners">{T(lang, 'Đối tác thị trường', 'Market Partner')}</Link></div></Card></div></div></Section></>;
}

export function MarketPartner({ lang }: Props) {
  const [form, setForm] = useState({ fullName: '', email: '', phone: '', country: 'Vietnam', intro: '' });
  const [status, setStatus] = useState<{ ok?: boolean; msg: string } | null>(null);
  async function submit(e: FormEvent) {
    e.preventDefault(); setStatus(null);
    if (!form.fullName.trim() || !form.email.trim()) { setStatus({ ok: false, msg: T(lang, 'Vui lòng nhập họ tên và email.', 'Please enter full name and email.') }); return; }
    const { error } = await supabase.from('partner_leads').insert({ full_name: form.fullName.trim(), email: form.email.trim(), phone: form.phone.trim(), country: form.country, intro: form.intro.trim(), source: 'market_partner_page', status: 'new' });
    if (error) setStatus({ ok: false, msg: T(lang, `Chưa lưu được đăng ký: ${error.message}`, `Application was not saved: ${error.message}`) });
    else { setStatus({ ok: true, msg: T(lang, 'Đã lưu đăng ký Đối tác thị trường. Admin sẽ duyệt hồ sơ.', 'Market Partner application saved. Admin will review it.') }); setForm({ fullName: '', email: '', phone: '', country: 'Vietnam', intro: '' }); }
  }
  const benefits = [T(lang, 'Hoa hồng minh bạch theo đơn hàng thực thu.', 'Transparent commission based on net paid orders.'), T(lang, 'Theo dõi chuyển đổi và referral trong dashboard sau khi được duyệt.', 'Track conversions and referrals in dashboard after approval.'), T(lang, 'Đồng hành phát triển cộng đồng doanh nghiệp Việt toàn cầu.', 'Help grow the global Vietnamese business community.')];
  return <><Hero lang={lang} kicker="Đối tác thị trường" kickerEn="Market Partner" title="Trở thành Đối tác thị trường của Deals68" titleEn="Become a Deals68 Market Partner" desc="Cùng Deals68 kết nối doanh nghiệp Việt, nhà đầu tư, người mua doanh nghiệp và đối tác chiến lược tại thị trường của bạn." descEn="Join Deals68 in connecting Vietnamese businesses, investors, business buyers and strategic partners in your market."/><Section><div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,minmax(0,1fr))', gap: 18 }} className="d68-form-2">{benefits.map((b, i) => <Card key={b} icon={['🌍','🤝','📊'][i]} title={T(lang, ['Phát triển cộng đồng','Giới thiệu cơ hội','Theo dõi minh bạch'][i], ['Community development','Opportunity referral','Transparent tracking'][i])}>{b}</Card>)}</div><form onSubmit={submit} style={{ maxWidth: 680, margin: '42px auto 0', background: '#EEF2F6', border: '1px solid #D5E0ED', borderRadius: 20, padding: 30 }}><h2 style={{ textAlign: 'center' }}>{T(lang, 'Đăng ký Đối tác thị trường', 'Register as Market Partner')}</h2><div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}><input style={input} value={form.fullName} onChange={(e) => setForm({ ...form, fullName: e.target.value })} placeholder={T(lang, 'Họ tên', 'Full name')} /><input style={input} type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="email@example.com" /><input style={input} value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} placeholder={T(lang, 'Số điện thoại', 'Phone')} /><select style={input} value={form.country} onChange={(e) => setForm({ ...form, country: e.target.value })}>{['Vietnam','United States','Canada','Australia','Germany','Singapore','Japan','South Korea','Other'].map((x) => <option key={x}>{x}</option>)}</select><textarea style={{ ...input, minHeight: 120 }} value={form.intro} onChange={(e) => setForm({ ...form, intro: e.target.value })} placeholder={T(lang, 'Giới thiệu bản thân / mạng lưới của bạn', 'About you / your network')} /><button style={{ background: '#0F2A4A', color: '#fff', fontWeight: 800, border: 'none', borderRadius: 11, padding: 14 }}>{T(lang, 'Gửi đăng ký', 'Submit application')}</button>{status ? <div style={{ padding: 12, borderRadius: 10, background: status.ok ? '#E9F9EF' : '#FDECEC', color: status.ok ? '#16A34A' : '#DC2626', fontWeight: 700 }}>{status.msg}</div> : null}</div></form></Section></>;
}
