export type LegalItem = {
  viTitle: string;
  enTitle: string;
  viParagraphs: string[];
  enParagraphs: string[];
  viBullets?: string[];
  enBullets?: string[];
};

export type BilingualCard = {
  viTitle: string;
  enTitle: string;
  viText: string;
  enText: string;
};

export const aboutLayers: BilingualCard[] = [
  { viTitle: "Thị trường cơ hội — Tạo cơ hội và thanh khoản", enTitle: "Opportunity marketplace — Creating opportunity and liquidity", viText: "Hồ sơ doanh nghiệp và tiêu chí nhà đầu tư được trình bày có cấu trúc để các bên khám phá, lọc, lưu và thể hiện quan tâm đối với những cơ hội phù hợp. Hồ sơ công khai có thể được ẩn danh nhằm bảo vệ danh tính doanh nghiệp trước khi có kết nối được chấp thuận.", enText: "Structured business profiles and investor criteria enable users to discover, filter, save and express interest in relevant opportunities. Public profiles may be anonymised to protect business identity until an approved connection is established." },
  { viTitle: "Phòng dữ liệu — Tạo dữ liệu, bằng chứng và niềm tin", enTitle: "Dataroom — Creating data, evidence and trust", viText: "Phòng dữ liệu giúp doanh nghiệp tập hợp tài liệu tài chính, pháp lý và vận hành; quản lý phiên bản; phân quyền truy cập; theo dõi lịch sử xem; và liên kết các chỉ số quan trọng với tài liệu nguồn. Dữ liệu được lấy từ phần mềm hoặc hệ thống nguồn làm tăng khả năng đối chiếu nhưng không thay thế kiểm toán hoặc thẩm định độc lập.", enText: "The Dataroom enables businesses to organise financial, legal and operating documents, manage versions, control access, track viewing activity and link key metrics to source evidence. Data imported from source systems improves traceability but does not replace an audit or independent due diligence." },
  { viTitle: "Lõi Chất lượng và Giá trị Doanh nghiệp — Giúp doanh nghiệp tốt hơn", enTitle: "Business Quality and Value Core — Helping businesses improve", viText: "Deals68 đánh giá mức độ đầy đủ của dữ liệu, mức sẵn sàng giao dịch và các vấn đề có thể ảnh hưởng đến quyết định của nhà đầu tư. Doanh nghiệp nhận được danh mục ưu tiên và kế hoạch cải thiện để nâng chất lượng quản trị, giảm rủi ro và trình bày cơ hội rõ ràng hơn.", enText: "Deals68 assesses data completeness, transaction readiness and issues that may affect investor decisions. Businesses receive prioritised improvement actions to strengthen management quality, reduce risk and present their opportunity more effectively." },
  { viTitle: "Không gian làm việc giao dịch — Tạo giao dịch hiệu quả hơn", enTitle: "Transaction workspace — Enabling more effective transactions", viText: "Các bên có thể quản lý thỏa thuận bảo mật điện tử, yêu cầu dữ liệu, hỏi đáp thẩm định, nhiệm vụ, cố vấn tham gia, ghi chú, tiến trình giao dịch và tài liệu ra quyết định trong cùng một không gian làm việc.", enText: "Parties can manage electronic confidentiality agreements, data requests, due diligence questions, tasks, advisor participation, notes, transaction stages and decision materials within a unified workspace." },
  { viTitle: "Theo dõi danh mục sau đầu tư — Tạo giá trị bền vững", enTitle: "Post-investment portfolio monitoring — Creating sustainable value", viText: "Sau khi giao dịch hoàn tất, doanh nghiệp và nhà đầu tư có thể tiếp tục theo dõi báo cáo định kỳ, kế hoạch so với thực tế, cam kết sau đầu tư, cảnh báo rủi ro và hành động khắc phục. Mục tiêu là duy trì minh bạch và hỗ trợ tạo giá trị lâu dài, không dừng lại ở việc kết nối ban đầu.", enText: "After completion, businesses and investors may continue to monitor periodic reporting, actual performance against plan, post-investment obligations, risk alerts and corrective actions. The objective is sustained transparency and long-term value creation, not merely an initial introduction." },
];

export const aboutBusinessValues = {
  vi: ["Tiếp cận nhà đầu tư, bên mua, bên cho vay và đối tác chiến lược phù hợp hơn với ngành, quy mô, quốc gia và mục tiêu giao dịch.", "Chuyển dữ liệu rời rạc thành hồ sơ có cấu trúc, có nguồn và có mức độ xác minh rõ ràng.", "Biết hồ sơ còn thiếu gì, vấn đề nào làm giảm khả năng giao dịch và hành động nào cần ưu tiên trong 30–90 ngày.", "Chuẩn bị phòng dữ liệu một lần và phân quyền cho nhiều bên theo từng giai đoạn.", "Nhận phản hồi có cấu trúc từ nhà đầu tư và cố vấn để cải thiện chất lượng doanh nghiệp.", "Duy trì báo cáo và theo dõi giá trị sau khi nhận vốn, bán cổ phần hoặc hình thành quan hệ đối tác."],
  en: ["Reach investors, buyers, lenders and strategic partners more closely matched by sector, size, geography and transaction objective.", "Convert fragmented information into a structured profile with clear sources and verification levels.", "Understand what is missing, which issues reduce transaction readiness and which actions should be prioritised over the next 30–90 days.", "Prepare a Dataroom once and grant staged access to multiple authorised parties.", "Receive structured feedback from investors and advisors to improve business quality.", "Continue reporting and value monitoring after investment, a share sale or a strategic partnership."],
};

export const aboutInvestorValues = {
  vi: ["Khám phá nguồn cơ hội doanh nghiệp tư nhân tại Việt Nam và trong mạng lưới doanh nghiệp Việt toàn cầu.", "Thiết lập tiêu chí đầu tư và nhận gợi ý có giải thích dựa trên mức độ phù hợp.", "Phân biệt dữ liệu tự khai, dữ liệu có tài liệu hỗ trợ, dữ liệu lấy từ hệ thống nguồn và dữ liệu được xác minh độc lập.", "Giảm thời gian sàng lọc bằng hồ sơ chuẩn hóa, cảnh báo rủi ro, so sánh cơ hội và danh mục thẩm định.", "Quản lý tiến trình, câu hỏi, tài liệu, cố vấn và bản ghi nhớ đầu tư trong một luồng thống nhất.", "Theo dõi khoản đầu tư và các hành động tạo giá trị sau giao dịch."],
  en: ["Discover private business opportunities in Vietnam and across the global Vietnamese business network.", "Configure investment criteria and receive explainable matching recommendations.", "Distinguish self-declared data, document-supported data, system-sourced data and independently verified information.", "Reduce screening time through standardised profiles, risk alerts, opportunity comparisons and due diligence checklists.", "Manage transaction stages, questions, documents, advisors and investment memoranda in one workflow.", "Monitor investments and value-creation actions after closing."],
};

export const aboutTrustPrinciples = {
  vi: ["Ẩn danh và công bố theo từng tầng: thông tin công khai, thông tin sau xác minh, thông tin sau thỏa thuận bảo mật và tài liệu thẩm định được tách biệt.", "Dữ liệu phải có nguồn: mỗi chỉ số quan trọng cần thể hiện nguồn, kỳ báo cáo, ngày cập nhật và mức độ xác minh nếu có.", "Không đánh đồng kết nối hệ thống với kiểm toán: dữ liệu nhập từ phần mềm kế toán hoặc bán hàng chỉ phản ánh hệ thống nguồn tại thời điểm đồng bộ.", "Quyết định thuộc về người dùng: phân tích, điểm số và hỗ trợ bằng trí tuệ nhân tạo chỉ phục vụ tham khảo, không thay thế thẩm định hoặc ý kiến chuyên môn.", "Theo dõi trách nhiệm: quyền truy cập, tài liệu, câu hỏi và hành động quan trọng được lưu vết phù hợp với quyền hạn và chính sách bảo mật."],
  en: ["Anonymity and staged disclosure: public information, verified-member information, post-NDA information and due diligence materials are separated.", "Data provenance: key metrics should identify their source, reporting period, update date and verification level where available.", "System integration is not an audit: information imported from accounting or sales systems reflects the source system at the time of synchronisation.", "Users remain the decision-makers: analytics, scores and AI-assisted outputs are for support only and do not replace due diligence or professional advice.", "Accountable workflows: access rights, documents, questions and material actions are logged in accordance with permissions and privacy policies."],
};
