-- Expand canonical Investor taxonomy aliases without fuzzy substring matching.
create or replace function public.normalize_investor_industry_key(raw_value text)
returns text
language sql
immutable
set search_path = public, pg_temp
as $$
  select case lower(trim(coalesce(raw_value, '')))
    when 'agriculture' then 'agriculture'
    when 'agri' then 'agriculture'
    when 'farm' then 'agriculture'
    when 'nông nghiệp' then 'agriculture'
    when 'nong nghiep' then 'agriculture'
    when 'automobile' then 'automobile'
    when 'automotive' then 'automobile'
    when 'auto' then 'automobile'
    when 'car' then 'automobile'
    when 'ô tô' then 'automobile'
    when 'o to' then 'automobile'
    when 'ô tô & phụ tùng' then 'automobile'
    when 'o to & phu tung' then 'automobile'
    when 'beauty & personal care' then 'beauty_personal_care'
    when 'beauty' then 'beauty_personal_care'
    when 'personal care' then 'beauty_personal_care'
    when 'spa' then 'beauty_personal_care'
    when 'làm đẹp & chăm sóc cá nhân' then 'beauty_personal_care'
    when 'lam dep & cham soc ca nhan' then 'beauty_personal_care'
    when 'beauty_personal_care' then 'beauty_personal_care'
    when 'building, construction & materials' then 'construction_materials'
    when 'construction & materials' then 'construction_materials'
    when 'construction' then 'construction_materials'
    when 'building materials' then 'construction_materials'
    when 'xây dựng & vật liệu' then 'construction_materials'
    when 'xay dung & vat lieu' then 'construction_materials'
    when 'construction_materials' then 'construction_materials'
    when 'chemicals' then 'chemicals'
    when 'chemical' then 'chemicals'
    when 'hóa chất' then 'chemicals'
    when 'hoa chat' then 'chemicals'
    when 'education' then 'education_training'
    when 'education & training' then 'education_training'
    when 'training' then 'education_training'
    when 'edtech' then 'education_training'
    when 'giáo dục & đào tạo' then 'education_training'
    when 'giao duc & dao tao' then 'education_training'
    when 'education_training' then 'education_training'
    when 'energy & utilities' then 'energy_utilities'
    when 'energy' then 'energy_utilities'
    when 'utilities' then 'energy_utilities'
    when 'renewable energy' then 'energy_utilities'
    when 'năng lượng & tiện ích' then 'energy_utilities'
    when 'nang luong & tien ich' then 'energy_utilities'
    when 'energy_utilities' then 'energy_utilities'
    when 'entertainment & leisure' then 'entertainment_leisure'
    when 'entertainment' then 'entertainment_leisure'
    when 'leisure' then 'entertainment_leisure'
    when 'giải trí & nghỉ dưỡng' then 'entertainment_leisure'
    when 'giai tri & nghi duong' then 'entertainment_leisure'
    when 'entertainment_leisure' then 'entertainment_leisure'
    when 'finance' then 'finance'
    when 'financial services' then 'finance'
    when 'fintech' then 'finance'
    when 'banking' then 'finance'
    when 'tài chính' then 'finance'
    when 'tai chinh' then 'finance'
    when 'f&b' then 'food_beverage'
    when 'fnb' then 'food_beverage'
    when 'food & beverage' then 'food_beverage'
    when 'food and beverage' then 'food_beverage'
    when 'restaurant' then 'food_beverage'
    when 'thực phẩm & đồ uống (f&b)' then 'food_beverage'
    when 'thực phẩm & đồ uống' then 'food_beverage'
    when 'thuc pham & do uong' then 'food_beverage'
    when 'food_beverage' then 'food_beverage'
    when 'healthcare' then 'healthcare'
    when 'health care' then 'healthcare'
    when 'health' then 'healthcare'
    when 'medical' then 'healthcare'
    when 'y tế & chăm sóc sức khỏe' then 'healthcare'
    when 'y tế & sức khỏe' then 'healthcare'
    when 'y te & cham soc suc khoe' then 'healthcare'
    when 'y te & suc khoe' then 'healthcare'
    when 'hotels & resorts' then 'hotels_resorts'
    when 'hotel & resort' then 'hotels_resorts'
    when 'hospitality' then 'hotels_resorts'
    when 'khách sạn & resort' then 'hotels_resorts'
    when 'khach san & resort' then 'hotels_resorts'
    when 'hotels_resorts' then 'hotels_resorts'
    when 'it & software' then 'it_software'
    when 'it & software / technology' then 'it_software'
    when 'technology' then 'it_software'
    when 'tech' then 'it_software'
    when 'software' then 'it_software'
    when 'saas' then 'it_software'
    when 'it' then 'it_software'
    when 'cntt' then 'it_software'
    when 'công nghệ' then 'it_software'
    when 'cong nghe' then 'it_software'
    when 'phần mềm' then 'it_software'
    when 'phan mem' then 'it_software'
    when 'it_software' then 'it_software'
    when 'manufacturing' then 'manufacturing'
    when 'factory' then 'manufacturing'
    when 'industrial' then 'manufacturing'
    when 'sản xuất' then 'manufacturing'
    when 'san xuat' then 'manufacturing'
    when 'media & advertising' then 'media_advertising'
    when 'media' then 'media_advertising'
    when 'advertising' then 'media_advertising'
    when 'marketing' then 'media_advertising'
    when 'truyền thông & quảng cáo' then 'media_advertising'
    when 'truyen thong & quang cao' then 'media_advertising'
    when 'media_advertising' then 'media_advertising'
    when 'real estate' then 'real_estate'
    when 'property' then 'real_estate'
    when 'bất động sản' then 'real_estate'
    when 'bat dong san' then 'real_estate'
    when 'bds' then 'real_estate'
    when 'real_estate' then 'real_estate'
    when 'retail' then 'retail'
    when 'store' then 'retail'
    when 'bán lẻ' then 'retail'
    when 'ban le' then 'retail'
    when 'services' then 'services'
    when 'service' then 'services'
    when 'business services' then 'services'
    when 'consulting' then 'services'
    when 'dịch vụ (b2b/b2c)' then 'services'
    when 'dịch vụ' then 'services'
    when 'dich vu' then 'services'
    when 'logistics' then 'transportation_logistics'
    when 'transportation & logistics' then 'transportation_logistics'
    when 'transport & logistics' then 'transportation_logistics'
    when 'transportation' then 'transportation_logistics'
    when 'warehouse' then 'transportation_logistics'
    when 'logistics & vận tải' then 'transportation_logistics'
    when 'logistics & van tai' then 'transportation_logistics'
    when 'vận tải' then 'transportation_logistics'
    when 'van tai' then 'transportation_logistics'
    when 'transportation_logistics' then 'transportation_logistics'
    when 'travel' then 'travel'
    when 'tourism' then 'travel'
    when 'du lịch' then 'travel'
    when 'du lich' then 'travel'
    when 'e-commerce' then 'ecommerce'
    when 'ecommerce' then 'ecommerce'
    when 'e commerce' then 'ecommerce'
    when 'marketplace' then 'ecommerce'
    when 'thương mại điện tử' then 'ecommerce'
    when 'thuong mai dien tu' then 'ecommerce'
    when 'textiles & apparel' then 'textiles_apparel'
    when 'textile & apparel' then 'textiles_apparel'
    when 'textiles' then 'textiles_apparel'
    when 'apparel' then 'textiles_apparel'
    when 'fashion' then 'textiles_apparel'
    when 'garment' then 'textiles_apparel'
    when 'dệt may & thời trang' then 'textiles_apparel'
    when 'det may & thoi trang' then 'textiles_apparel'
    when 'textiles_apparel' then 'textiles_apparel'
    when 'seafood & export' then 'seafood_export'
    when 'seafood' then 'seafood_export'
    when 'aquaculture' then 'seafood_export'
    when 'export' then 'seafood_export'
    when 'thủy sản & xuất khẩu' then 'seafood_export'
    when 'thuy san & xuat khau' then 'seafood_export'
    when 'seafood_export' then 'seafood_export'
    else null
  end
$$;

create or replace function public.normalize_investor_deal_type(raw_value text)
returns text
language sql
immutable
set search_path = public, pg_temp
as $$
  select case lower(trim(coalesce(raw_value, '')))
    when 'investment' then 'Investment'
    when 'invest' then 'Investment'
    when 'fundraise' then 'Investment'
    when 'fundraising' then 'Investment'
    when 'equity' then 'Investment'
    when 'partial stake sale' then 'Investment'
    when 'minority investment' then 'Investment'
    when 'đầu tư thiểu số' then 'Investment'
    when 'đầu tư' then 'Investment'
    when 'gọi vốn' then 'Investment'
    when 'bán cổ phần' then 'Investment'
    when 'lending' then 'Lending'
    when 'loan' then 'Lending'
    when 'debt' then 'Lending'
    when 'debt/loan' then 'Lending'
    when 'debt / loan' then 'Lending'
    when 'debt financing' then 'Lending'
    when 'vay vốn' then 'Lending'
    when 'cho vay' then 'Lending'
    when 'm&a' then 'M&A'
    when 'ma' then 'M&A'
    when 'acquisition' then 'M&A'
    when 'full acquisition' then 'M&A'
    when 'business sale' then 'M&A'
    when 'chuyển nhượng' then 'M&A'
    when 'partnership / jv' then 'Partnership / JV'
    when 'partnership' then 'Partnership / JV'
    when 'strategic partnership' then 'Partnership / JV'
    when 'jv' then 'Partnership / JV'
    when 'joint venture' then 'Partnership / JV'
    when 'đối tác / liên doanh' then 'Partnership / JV'
    when 'liên doanh' then 'Partnership / JV'
    else null
  end
$$;
