import { expect, Page, TestInfo } from '@playwright/test';
import contract from '../specs/deals68-v1_3-contract.json' assert { type: 'json' };

export const BASE_URL = process.env.D68_BASE_URL || contract.previewDefault;
export const publicRoutes: string[] = contract.routes.public;
export const privateRoutes: string[] = contract.routes.private;
export function annotate(testInfo: TestInfo, type: string, description: string) { testInfo.annotations.push({ type, description }); }
export async function collectConsoleErrors(page: Page) { const errors: string[] = []; page.on('console', (msg) => { if (msg.type() === 'error') errors.push(msg.text()); }); page.on('pageerror', (err) => errors.push(err.message)); return errors; }
export async function gotoAndWait(page: Page, route: string) { const response = await page.goto(route, { waitUntil: 'domcontentloaded' }); await page.waitForLoadState('networkidle', { timeout: 12_000 }).catch(() => undefined); return response; }
export async function expectNoCriticalConsoleErrors(errors: string[]) { const critical = errors.filter((x) => !/favicon|ResizeObserver|net::ERR_ABORTED/i.test(x)); expect(critical, `Console/page errors:\n${critical.join('\n')}`).toEqual([]); }
export async function expectNoHorizontalOverflow(page: Page) { const overflow = await page.evaluate(() => Math.max(0, document.documentElement.scrollWidth - document.documentElement.clientWidth)); expect(overflow, `Horizontal overflow ${overflow}px`).toBeLessThanOrEqual(2); }
export async function expectNoBadPlaceholders(page: Page) { const text = await page.locator('body').innerText({ timeout: 8000 }); const bad = ['undefined','null','NaN','[object Object]'].filter((w) => text.includes(w)); expect(bad, `Bad placeholders visible: ${bad.join(', ')}`).toEqual([]); }
export async function expectPageHasMeaningfulContent(page: Page) { await expect(page.locator('body')).toBeVisible(); const text = (await page.locator('body').innerText()).trim(); expect(text.length, 'Page text length').toBeGreaterThan(80); const h1h2 = await page.locator('h1,h2').count(); expect(h1h2, 'At least one H1/H2').toBeGreaterThan(0); }
export async function expectInternalLinksHealthy(page: Page, maxLinks = 35) { const hrefs = await page.locator('a[href]').evaluateAll((nodes) => Array.from(new Set(nodes.map((a) => (a as HTMLAnchorElement).getAttribute('href') || '')))); const internal = hrefs.filter((href) => href && !href.startsWith('#') && !href.startsWith('mailto:') && !href.startsWith('tel:') && !href.startsWith('http') && !href.startsWith('javascript:')).slice(0, maxLinks); for (const href of internal) { const res = await page.request.get(href, { maxRedirects: 2 }).catch(() => null); expect(res?.status(), `Internal link should not be dead: ${href}`).toBeLessThan(500); } }
export function maybeSkipAuth(testInfo: TestInfo, reason = 'Set D68_E2E_RUN_AUTH=1 and provide test credentials/OTP source to run destructive/auth workflows.') { if (process.env.D68_E2E_RUN_AUTH !== '1') { testInfo.annotations.push({ type:'skipped-by-design', description:reason }); return true; } return false; }
export async function login(page: Page, email: string, password: string, role: 'business'|'investor'|'admin'='business') { await gotoAndWait(page, role === 'admin' ? '/admin/login' : `/login?role=${role}`); await page.getByLabel(/email|Tên đăng nhập|username/i).fill(email); await page.getByLabel(/Mật khẩu|Password/i).fill(password); await page.getByRole('button', { name: /Đăng nhập|Log in/i }).click(); await page.waitForLoadState('networkidle').catch(() => undefined); }
